/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Translated to a": "转换为一个",
    "Universe Time - made by": "宇宙时间 - 由",
    "Upgrades": "升级",
    "x": "x",
    "x exponent on Slepton's effect": "x 斯莱普顿效应的指数",
    "x multiplier on quarks gain": "x 夸克增益的乘数",
    "x multiplier on spacetime gain": "x 时空增益乘数",
    "x multiplier on supersymmetry particles gain": "x 超对称粒子增益的乘数",
    "x multiplier on the fabric of time gain": "x 时间增益结构上的乘数",
    "x multiplier on universe time formula": "宇宙时间公式的x乘数",
    "x speed on inflation growth": "x 通胀增长速度",
    "You completed the game in": "你完成了游戏",
    "You played": "你玩过",
    "Your universe time is": "你的宇宙时间是",
    "Atoms": "原子",
    "Atoms, which is generated based on rewards": "Atoms，基于奖励生成",
    "Break Supersymmetry for": "打破超对称性",
    "break_eternity.js": "break_eternity.js",
    "Breaking Supersymmetry will reset everything except universe time": "打破超对称会重置宇宙时间以外的一切",
    "by": "",
    "Chargino, translated to a": "Chargino，转换为",
    "Congratulations!": "恭喜！",
    "Electron": "电子",
    "Element.js by": "Element.js 由",
    "Fabric of time": "时间结构",
    "fabric of time, which is generated based on your Universe time": "时间结构，根据你的宇宙时间生成",
    "Fabric Time": "时间结构",
    "Hard Reset": "硬重置",
    "Hello, world!": "你好世界！",
    "in": "在",
    "Inflation": "通货膨胀",
    "Jacorb90": "Jacorb90",
    "JAM winter 2022": "JAM 2022 年冬季",
    "Join my Discord server": "加入我的 Discord 服务器",
    "Loading Game...": "游戏加载中...",
    "Main": "首页",
    "MrRedShark77": "MrRedShark77",
    "Neutralino, translated to an": "Neutralino，转换为",
    "Neutron": "中子",
    "of Universe time": "宇宙时间",
    "old": "那么老",
    "on this game...": "在这个游戏...",
    "Options": "选项",
    "Patashu": "帕塔舒",
    "Proton": "质子",
    "quarks": "夸克",
    "Quarks": "夸克",
    "Rewards": "奖励",
    "Rewards (next at": "奖励（下一个",
    "Slepton, translated to": "斯莱普顿，转换为",
    "Spacetime": "时空",
    "spacetime, which appends to": "时空，它附加到",
    "Squark, translated to a": "夸克，转换为",
    "Supersymmetry": "超对称",
    "Supersymmetry Particle, which generates": "超对称粒子，生成",
    "Supersymmetry Particles": "超对称粒子",
    "Supersymmetry Powers every second": "每秒超对称的力量",
    "Supported files": "支持的文件",
    "Thanks for playing!": "感谢参与！",
    " Breaking Supersymmetry will reset everything except universe time": "打破超对称会重置宇宙时间以外的一切",
    " Cost": "成本",
    " Currently": "现在",
    " Electrons are 2.5% stronger.": "电子强 2.5%。",
    " Element.js by": "Element.js 由",
    " Gain 10% of Supersymmetry particles gained on reset.": "重置时获得 10% 的超对称粒子。",
    " Gain 20x more Spacetime.": "获得 20 倍以上的时空。",
    " Gain more atoms based on quarks.": "基于夸克获得更多原子。",
    " Gain more atoms based on spacetime.": "根据时空获得更多原子。",
    " Gain more atoms based on Universe Time.": "根据宇宙时间获得更多原子。",
    " Gain more fabric of time based on supersymmetry particles.": "基于超对称粒子获得更多时间结构。",
    " Gain more quarks based on atoms.": "基于原子获得更多的夸克。",
    " Gain more quarks based on Inflation.": "根据通货膨胀获得更多夸克。",
    " Gain more quarks based on spacetime.": "根据时空获得更多夸克。",
    " Gain more quarks based on supersymmetry particles.": "基于超对称粒子获得更多夸克。",
    " Gain more spacetime based on the fabric of time.": "根据时间结构获得更多时空。",
    " haha you found a secret before quark version": "哈哈你在夸克版之前发现了一个秘密",
    " Inflation adds its base at a reduced rate. The inflation effect is raised by 2": "通货膨胀以较低的速度增加其基础。通货膨胀效应提高了 2",
    " Inflation boost the fabric of time gain.": "通货膨胀促进了时间收益的结构。",
    " Keep ^0.5 of Inflation gained on reset.": "重置时保持 ^0.5 的通货膨胀。",
    " Neutrons are 10% stronger.": "中子强 10%。",
    " Protons are 25% stronger.": "质子强 25%。",
    " Raise Inflation's effect based on Slepton.": "根据斯莱普顿提高通货膨胀的效果。",
    " Raise inflation's exponent to the 1.1th power.": "将通货膨胀的指数提高到 1.1 次方。",
    " Raise Quarks gain to the 1.025th power.": "将夸克增益提高到 1.025 次方。",
    " Raise Spacetime & Supersymmetry particles gains to the 1.1th power.": "将时空和超对称粒子增益提高到 1.1 次方。",
    " Raise the fabric of time to the 1.1th power.": "将时间结构提高到 1.1 次方。",
    " Reward's requirement is cheaper based on the fabric of time.": "根据时间结构，奖励的要求更便宜。",
    " Spacetime adds to Inflation growth's base.": "时空增加了通货膨胀增长的基础。",
    " Spacetime boost its gain.": "时空提高了它的收益。",
    " Spacetime gain softcap is weaker based on atoms.": "基于原子的时空增益软上限较弱。",
    " Spacetime Upgrade 7 is twice as effective.": "时空升级 7 的效果是原来的两倍。",
    " Speed inflation growth based on rewards.": "基于奖励加速通胀增长。",
    " Start to generate spacetime each time.": "每次开始产生时空。",
    " Supersymmetry's effect exponent is increased based on the fabric of time.": "超对称的影响指数随着时间的变化而增加。",
    " Supported files": "支持的文件",
    " The fabric of time gain's exponent is increased by 2.": "时间增益指数的结构增加了 2。",
    " Triple quarks gain for each upgrade bought.": "每次购买升级都会获得三倍夸克。",
    " Universe Time - made by": "宇宙时间 - 由",
    " Universe time boost spacetime gain at a reduced rate.": "宇宙时间以降低的速率提高时空增益。",
    " Universe time boost Supersymmetry particles gain.": "宇宙时间提升超对称粒子增益。",
    " Universe time formula is multiplied by spacetime.": "宇宙时间公式乘以时空。",
    " Universe time's formula softcap is weaker based on Inflation.": "宇宙时间的公式软上限基于通货膨胀而较弱。",
    " You played": "你玩了",
    " \n                    Cost": " \n                    成本",
    "/s) Inflation, translated to a": "/s) 通货膨胀，转换为",
    "Copied to clipboard": "已复制到剪切板",
    "Game Saved": "游戏已保存",
    "(softcapped": "(软上限",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Quark Era": "夸克时代",
    "The fabric of Time Era": "时间结构时代",
    "Post-Inflation Era": "后通胀时代",
    "Time Begins Era": "时间开始时代",
    "Inflation Era": "通胀时代",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)zs$/,
    /^([\d\.]+)fs$/,
    /^([\d\.]+)ps$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)×([\d\.,]+)\^([\d\.,]+)$/,
    /^([\d\.,]+)tP$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)tP$/,
    /^([\d\.]+)×([\d\.,]+)\^([\d\.,]+)tP$/,
    /^([\d\.]+)×([\d\.,]+)\^([\d\.,]+)x$/,
    /^([\d\.]+)×([\d\.,]+)\^([\d\.,]+) \(\+([\d\.]+) OoM$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^(.+) \(\+(.+)\/sec$/, '$1 \(\+$2\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)\% weaker$/, '$1\% 更弱'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)x cheaper$/, '$1x 更便宜'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);